<!DOCTYPE html>
<html lang="en">
<head>
    <title>try catch finally 구문 사용</title>
</head>
<body>
    <script>
        /* 요약 : try catch(e) finally 로 동작은 계속 실행하게 만들면서, 오류는 잡아낼 수 있다. */
        
        function test(data){
            try{
                // 일단, try해라.
                throw(new Error('에러갑니다!'));
                console.log(data+' 입니다.');
            }catch(e){
                // try에서 문제 생기면 바로 catch 실행.
                console.log('catch에서 받은 에러: '+e);
                // 매개 변수로 에러에 대한 내용을 받을 수 있다.

                return;
            }finally{
                console.log('함수 실행을 마칩니다.');
                // 없어도 실행되지만, 무족권 실행 되는 것을 확정하기 위해서 사용하는
                // 비교적 채-신 구문.

                // return이 있어도 실행한다.

                // try, catch가 어떻든, return이 있든 없든, 문제가 생기든 말든,
                // 무족권 실행.
            }
            console.log('함수 실행을 마칩니다.');
            // return이 있으면 실행 불가.

            // 그냥 쓰로우만 사용하면, 함수를 마저 실행하지 못 하고, 종료.
            // try, catch를 사용하면 함수 실행은 유지가 된다.
        }
    </script>
</body>
</html>